### ISSUE TITLE
OpenType Set "No Tails" not working on letter "d" & "u"

### ISSUE THREAD

**Issue by yolanare** [JiriKrblich/Mluvka#1]
Hi ! Really nice font I like it a lot. I've found some problems with one of the OpenType sets.
The title is self-explanatory I think.
OpenType Set "No Tails" not working on letter "d" & "u"
See the letter "a" for reference

I'm using Mluvka v2.000
On Adobe Illustrator 28.1

![no tails not working d](https://github.com/JiriKrblich/Mluvka/assets/53494809/e4a3f3b9-47a4-4b4a-be6a-45003d3ccae1)

**Comment by JiriKrblich** [comment]
Thank you! I will try to fix it!
